WITH CTE AS(
SELECT *, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS CLASS
FROM ECOLI_DATA)

SELECT E.ID, CASE
    WHEN C.CLASS = 1 THEN 'CRITICAL'
    WHEN C.CLASS = 2 THEN 'HIGH'
    WHEN C.CLASS = 3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS 'COLONY_NAME'
    
FROM ECOLI_DATA E JOIN CTE C
    ON E.ID = C.ID
